version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


  db:
    # environment:
    #   - POSTGRES_DB=resourcery_dev
    # For linking services.
    # expose:
    #   - '5432'
    image: postgres
    # For exposing to host machine.
    ports:
      - '5432:5432'

