env: "_env:SERVER_ENV:Localhost"
port: "_env:SERVER_PORT:7777"
dbConfig:
  dbPort: "_env:DB_PORT:5432"
  dbHost: "_env:DB_HOST:localhost"
  dbUser: "_env:DB_USER:postgres"
  dbPass: "_env:DB_PASS:''"
  dbName: "_env:DB_NAME:postgres"
poolConfig:
  stripes: "_env:POOL_STRIPES:2"
