name: resourcery
version: '0.0.1'
category: Web
author: Austin Erlandson
maintainer: austin@erlandson.com
copyright: 2018 Austin Erlandson
license: MIT
github: erlandsona/resourcery
# extra-source-files:
#   - ../README.md

dependencies:
  - base >=4.7 && <5

  # Utility Libs
  # - bytestring
  # - elm-export
  # - elm-export-persistent
  # - filepath
  # - hilt
  # - monad-logger
  # - mtl
  # - http-types
  # - safe
  # - template-haskell
  # - require # Add if needed by project modules.
  - text
  # - time
  # - transformers
  # - turtle
  - yaml

  # Serialization / DeSerialization
  - aeson

  # DB
  - beam-core
  - beam-postgres
  # - beam-migrate # Add when ready
  - postgresql-simple
  - resource-pool

  # Web API Framework
  # - servant-docs
  # - servant-elm
  # - servant-foreign
  # - servant-generic
  - servant-server

  # Haskell Web Server like Puma & Rack from Ruby.
  - wai
  # - wai-app-static
  # - wai-cors
  # - wai-extra
  - warp


default-extensions:
  - OverloadedStrings

library:
  source-dirs:
    - library
  when:
    - condition: (flag(dev)) || (flag(library-only))
      then:
        ghc-options:
        # - -F -pgmF requirepp
        - -Wall
        - -Werror
        - -fwarn-tabs
        - -ddump-deriv
        - -ddump-splices
        - -fno-warn-orphans
        - -O0
        cpp-options: -DDEVELOPMENT
      else:
        ghc-options:
        # - -F -pgmF requirepp
        - -Wall
        - -Werror
        - -fwarn-tabs
        - -O2

executables:
  resourcery:
    main: Server.hs
    source-dirs: executables
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - resourcery
    when:
      - condition: flag(library-only)
        buildable: false

  # docs:
  #   <<: *defaults
  #   main: exe/Docs.hs
  #   source-dirs: exec

  # elmify:
  #   <<: *defaults
  #   main: exe/Elmify.hs

  # seed:
  #   <<: *defaults
  #   main: db/Seeds.hs

tests:
  resourcery-test:
    main: test/Spec.hs
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - resourcery
      - hspec
      - text
      - neat-interpolation

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
